import './globals.css'
import { Inter, IBM_Plex_Sans_Thai } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin', 'thai']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibmPlexSansThai.className}>{children}</body>
    </html>
  )
}
